name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # checks code from repo
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup  node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: install dpendencies
        run: npm install

      - name: run build
        run: npm run build

      - name: run test
        run: npm test -- --passWithNoTests
